version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Use service name for Kafka's internal DNS
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres  # Matches DB_USER
      POSTGRES_PASSWORD: 123  # Matches DB_PASSWORD
      POSTGRES_DB: polling_system  # Matches DB_NAME

  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polling-backend
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_USER: postgres  # Matches your provided DB_USER
      DB_PASSWORD: 123  # Matches your provided DB_PASSWORD
      DB_HOST: postgres  # Use 'postgres', the service name in Docker Compose
      DB_PORT: 5432  # Matches DB_PORT
      DB_NAME: polling_system  # Matches DB_NAME
      KAFKA_BROKER: kafka:9092  # Matches your Kafka broker address
      ZOOKEEPER_HOST: zookeeper:2181  # Matches your Zookeeper host
    depends_on:
      - kafka
      - postgres
